app_name: Nikora Promo Orders Transformer — Plain Logic
policy:
  incoming_orders_are_non_changeable: true
  use_dates_from_order_file: false
  no_deletions: true
files:
  barcode_map: config/barcode_map.xlsx
  shop_schedule: config/shop_schedule.xlsx
mapping:
  new_col: ძირითადი შტრიხკოდი
  old_col: შტრიხკოდი
  description: 'Replace order barcodes using this 2-column Georgian list: old (col2)
    -> new (col1).'
order:
  barcode_candidates:
  - EAN
  - ean
  - Barcode
  - barcode
  - SKU
  - sku
  - შტრიხკოდი
  shop_candidates:
  - ShopID
  - shop_id
  - Shop
  - shop
  - StoreID
  - store_id
  - Store
  - store
  - ობიექტი
  - მაღაზია
  force_barcode_column: null
  force_shop_column: null
schedule:
  force_shop_column: null
  force_weekday_column: null
  weekday_accepts:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - ორშაბათი
  - სამშაბათი
  - ოთხშაბათი
  - ხუთშაბათი
  - პარასკევი
normalization:
  shop_trim: true
  shop_upper: true
output:
  filename_pattern: ნიკორა, {weekday_geo}, {date}.xlsx
  zip_name: ნიკორა, დაგრუპული დღეებით, {date}.zip
  date_format: '%Y-%m-%d'
  include_unassigned: true
